version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: accounts
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    volumes:
      - ./db_backup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      #- "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11211:11211"
  
  tomcat:
   build: .
    #context: .
    #dockerfile: Dockerfile
   container_name: tomcat
   depends_on:
    - mysql
    - rabbitmq
    - memcached
   ports:
    - "8080:8080"
   environment:
    DB_HOST: mysql
    DB_PORT: 3306
    DB_NAME: accounts
    DB_USER: admin
    DB_PASS: admin123
    RABBIT_HOST: rabbitmq
    MEMCACHED_HOST: memcached

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - tomcat
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      